site_name: Zhiyuan Chen
site_url: https://zyc.ai
site_author: Zhiyuan Chen
site_description: The website of Zhiyuan Chen
copyright: All rights reserved &copy; Zhiyuan Chen 2017-2022

repo_name: Zhiyuan Chen
repo_url: https://github.com/ZhiyuanChen

nav:
  - Zhiyuan Chen: index.md
  # - 联想研究院:
  #   - 联想研究院实习总结: lenovo_research.md
  - PyTorch:
    - nn.Module: pytorch/nn/Module.md
    - 分布式: pytorch/distributed.md
  - 统计:
    - 概率论: stat/probability.md
  - 优化:
    - 优化: optimisation/introduction.md
    - 仿射与凸: optimisation/affine_convex.md
    - 球与锥: optimisation/ball_cone.md
    - 超平面、半空间与多面体: optimisation/hyperplane_halfspace_polyhedra.md
    - 对偶锥与广义不等式: optimisation/dual_cone_generalized_inequality.md
    - 凸凹: optimisation/convex_concave.md
  #- 机器学习:
  #  - 统计: ml/statistics.md
  - 计算机视觉:
    - Big Transfer: vision/big_transfer.md
  - 变换网络:
    - 注意力: transformer/attention.md
    - Visual Transformer: transformer/visual_transformer.md
    - Vision Transformer: transformer/vision_transformer.md
    - Early Convolutions: transformer/early_convolutions.md
  - 基模型:
    - CLIP: foundation/clip.md
    - Uni-Perceiver: foundation/uniperceiver.md
  - 自监督学习:
    - SimCLR: ssl/SimCLR.md
    - SimCLRv2: ssl/SimCLRv2.md
  #  - SiamRPN: vision/siamrpn.md
  # - 生物医学影像:
  #   - 超声: bmi/ultrasound.md
  # - 算法:
  #   - 算法导论: algorithm/introduction.md
  #   - 复杂度: algorithm/complexity.md
  #   - 树: algorithm/tree.md
  #   - 递推方程: algorithm/recurrence_relation.md
  - 容器:
    - Kubernetes:
      - Kubernetes: container/k8s/introduction.md
      - 组件: container/k8s/component.md
      - 安装: container/k8s/installation.md
      - Pods: container/k8s/pods.md
      - Deployments: container/k8s/deployments.md
    - Docker:
      - 导论: container/docker/introduction.md
      - 安装: container/docker/installation.md
      - 命令行接口: container/docker/command_line_interface.md
      - Dockerfile: container/docker/dockerfile.md
  - 随笔:
    - 文档:
      - 设计模式: sketch/document/design_pattern.md
      - 属性访问慢吗？: sketch/document/attribute_lookup.md
      - JetBrains使用指南: sketch/document/jetbrains.md
    - 职业:
      - 元人工智能Residency面经: sketch/career/interview_fair_residency.md
      - 如何准备面试: sketch/career/prepare_interview.md
      - ResNet面试简介: sketch/career/interview_resnet.md
      - 实习面试总结: sketch/career/internship_interview_summary.md
      - 秋招总结: sketch/career/campus_recruitment_summary.md
      - 写给没有通过面试的同学: sketch/career/to_unfit_applicants.md
      - 写给通过面试的同学: sketch/career/to_fit_applicants.md
    - 评测:
      - iPad Pro简评: sketch/review/ipad_brief.md
      - iPad是否可以担任中短途旅行中的主力计算机: sketch/review/ipad_trip.md
      - 不要买分体式键盘: sketch/review/split_keyboard.md
    - 日记:
      - 二〇一九年 六月 十日: sketch/diary/20190610.md
      - 二〇一九年 十一月 八日: sketch/diary/20191108.md
      - 二〇二〇年 四月 四日: sketch/diary/20200404.md
      - 二〇二〇年 十月 六日: sketch/diary/20201006.md
      - 辛丑年度总结: sketch/diary/2021.md
    - 致敬我们终将过时的电脑: sketch/tribute_to_computers.md
    - 一个Windows爱好者的叛变: sketch/betray_windows.md
    - 青海-成长历程分享: sketch/growth_experience.md
    - 食品储备: sketch/food_reserve.md
  - 关于:
    - 禅: about/zen.md
    - 服务协议: about/sa.md
    - 最终用户许可协议: about/eula.md
    - 隐私声明: about/privacy.md
    - 评论政策: about/comment.md
    - 贡献: about/contribute.md
    - 捐赠: about/donate.md

theme:
  name: material
  custom_dir: overrides
  language: 'zh'
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  logo: 'assets/images/logo.png'
  favicon: 'assets/images/logo.ico'
  features:
    - announce.dismiss
    - header.autohide
    - navigation.expand
    # - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    # - navigation.tabs.sticky
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font: false

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
  analytics:
    provider: google
    property: 'G-HJPHFP4Y4Y'
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better. Please check out our
      <a href="https://zyc.ai/about/privacy">Privacy Policy</a> for more information.
  # disqus: 'zycai'
  generator: false
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/ZhiyuanChen'
    - icon: fontawesome/brands/gitlab
      link: 'https://gitlab.com/ZhiyuanChen'
    - icon: fontawesome/brands/bitbucket
      link: 'https://bitbucket.org/ZhiyuanChen'
    - icon: fontawesome/solid/paper-plane
      link: mailto:this@zyc.ai
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/zyc.fb
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zyc_ai
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/zyc.ai
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/%E9%99%9F%E5%8E%9F-%E9%99%88-0b473aa9/'

  # version:
  #   method: mike

extra_css:
  - assets/fonts/fonts.css

extra_javascript: 
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/shortcuts.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - mdx_math
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty
  - tables
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: true

plugins:
  - awesome-pages
  - bibtex:
      bib_file: "docs/references.bib"
      csl_file: "https://raw.githubusercontent.com/citation-style-language/styles/master/ieee.csl"
      cite_inline: true
  - git-revision-date-localized:
      type: iso_datetime
  - git-committers
  # - privacy:
  #     externals_exclude:
  #       - cdn.jsdelivr.net/npm/mathjax@3/*
  #       - giscus.app/*
  - search
  - tags
